# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: 'OWF Learn / Documenting'
pages:
- Home: index.md
- Introduction: introduction.md
- Documenting Datasets: doc-datasets.md
- Documenting Processes: doc-processes.md
- Documenting Software: doc-software.md
- Documenting APIs: doc-apis.md
- Documenting Projects: doc-projects.md
- Reference - GitHub: ref-github.md
- Reference - Google Docs: ref-google-docs.md
- Reference - HTML: ref-html.md
- Reference - Jeckyll: ref-jeckyll.md
- Reference - Markdown: ref-markdown.md
- Reference - MkDocs: ref-mkdocs.md
- Reference - Word & PDF: ref-word-pdf.md
- 'Resources': resources.md
# ------- configuration properties ---------------
# Use Material theme
# - installation notes:  https://github.com/squidfunk/mkdocs-material
theme: material
#theme: readthedocs
# Don't indicate the repo because Edit will be shown on every page (don't want that in deployed mode)
# - Also see edit_uri if repo_url is specified
#repo_url:  https://github.com/OpenWaterFoundation/owf-learn-documenting
site_description:  'Open Water Foundation Learn Documenting'
site_author:  'Open Water Foundation'
site_favicon:  'images/OWF-Logo-Favicon-32x32.png'
copyright:  'Copyright Open Water Foundation'
# Use extra CSS to customize styles
extra_css:
  - 'css/extra-material-theme.css'
